export const CREATE_USER_SUCCESS = 'USER_AUTH_SUCCESS';
export const CREATE_USER_ERROR = 'USER_AUTH_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const USER_AUTH = 'USER_AUTH';

export const USER_LOGOUT = 'USER_LOGOUT';

export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAN_ALERT = 'CLEAN_ALERT';

export const FILE_UPLOAD = 'FILE_UPLOAD';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';


export const LINK_CREATED_SUCCESS = 'LINK_CREATED_SUCCESS';
export const LINK_CREATED_ERROR = 'LINK_CREATED_ERROR';
export const CLEAN_STATE = 'CLEAN_STATE';

export const AGREGAR_DESCARGAS = 'AGREGAR_PASSWORD';
export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD';